// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBazsr4GTlWF8uY2V0eGuoLilpqDouzEUA',
    appId: '1:620272123882:web:77793cb39c844adcdd7c93',
    messagingSenderId: '620272123882',
    projectId: 'tasktodo-abir-2026',
    authDomain: 'tasktodo-abir-2026.firebaseapp.com',
    storageBucket: 'tasktodo-abir-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBKPfhSp7H2ASCP0IzGfeg5RNo-6fVQi8',
    appId: '1:620272123882:android:3b8e442d2828de8fdd7c93',
    messagingSenderId: '620272123882',
    projectId: 'tasktodo-abir-2026',
    storageBucket: 'tasktodo-abir-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBflN9dFcnxl_5kZFzrVHnly2FpDMXnSE',
    appId: '1:620272123882:ios:2a1500c317794725dd7c93',
    messagingSenderId: '620272123882',
    projectId: 'tasktodo-abir-2026',
    storageBucket: 'tasktodo-abir-2026.firebasestorage.app',
    iosBundleId: 'com.example.tasktodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBflN9dFcnxl_5kZFzrVHnly2FpDMXnSE',
    appId: '1:620272123882:ios:2a1500c317794725dd7c93',
    messagingSenderId: '620272123882',
    projectId: 'tasktodo-abir-2026',
    storageBucket: 'tasktodo-abir-2026.firebasestorage.app',
    iosBundleId: 'com.example.tasktodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBazsr4GTlWF8uY2V0eGuoLilpqDouzEUA',
    appId: '1:620272123882:web:87707e83a700d41bdd7c93',
    messagingSenderId: '620272123882',
    projectId: 'tasktodo-abir-2026',
    authDomain: 'tasktodo-abir-2026.firebaseapp.com',
    storageBucket: 'tasktodo-abir-2026.firebasestorage.app',
  );
}
